// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Postgresql.V1
{

    /// <summary>
    /// Most recently observed status of the backup. This data may not be up to date. Populated by the system. Read-only. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status
    /// </summary>
    [OutputType]
    public sealed class BackupStatus
    {
        /// <summary>
        /// The credentials to use to upload data to Azure Blob Storage
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Postgresql.V1.BackupStatusAzurecredentials AzureCredentials;
        /// <summary>
        /// The ID of the Barman backup
        /// </summary>
        public readonly string BackupId;
        /// <summary>
        /// The Name of the Barman backup
        /// </summary>
        public readonly string BackupName;
        /// <summary>
        /// The starting xlog
        /// </summary>
        public readonly string BeginLSN;
        /// <summary>
        /// The starting WAL
        /// </summary>
        public readonly string BeginWal;
        /// <summary>
        /// The backup command output in case of error
        /// </summary>
        public readonly string CommandError;
        /// <summary>
        /// Unused. Retained for compatibility with old versions.
        /// </summary>
        public readonly string CommandOutput;
        /// <summary>
        /// The path where to store the backup (i.e. s3://bucket/path/to/folder) this path, with different destination folders, will be used for WALs and for data. This may not be populated in case of errors.
        /// </summary>
        public readonly string DestinationPath;
        /// <summary>
        /// Encryption method required to S3 API
        /// </summary>
        public readonly string Encryption;
        /// <summary>
        /// The ending xlog
        /// </summary>
        public readonly string EndLSN;
        /// <summary>
        /// The ending WAL
        /// </summary>
        public readonly string EndWal;
        /// <summary>
        /// EndpointCA store the CA bundle of the barman endpoint. Useful when using self-signed certificates to avoid errors with certificate issuer and barman-cloud-wal-archive.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Postgresql.V1.BackupStatusEndpointca EndpointCA;
        /// <summary>
        /// Endpoint to be used to upload data to the cloud, overriding the automatic endpoint discovery
        /// </summary>
        public readonly string EndpointURL;
        /// <summary>
        /// The detected error
        /// </summary>
        public readonly string Error;
        /// <summary>
        /// The credentials to use to upload data to Google Cloud Storage
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Postgresql.V1.BackupStatusGooglecredentials GoogleCredentials;
        /// <summary>
        /// Information to identify the instance where the backup has been taken from
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Postgresql.V1.BackupStatusInstanceid InstanceID;
        /// <summary>
        /// The last backup status
        /// </summary>
        public readonly string Phase;
        /// <summary>
        /// The credentials to use to upload data to S3
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Postgresql.V1.BackupStatusS3credentials S3Credentials;
        /// <summary>
        /// The server name on S3, the cluster name is used if this parameter is omitted
        /// </summary>
        public readonly string ServerName;
        /// <summary>
        /// When the backup was started
        /// </summary>
        public readonly string StartedAt;
        /// <summary>
        /// When the backup was terminated
        /// </summary>
        public readonly string StoppedAt;

        [OutputConstructor]
        private BackupStatus(
            Pulumi.Kubernetes.Types.Outputs.Postgresql.V1.BackupStatusAzurecredentials azureCredentials,

            string backupId,

            string backupName,

            string beginLSN,

            string beginWal,

            string commandError,

            string commandOutput,

            string destinationPath,

            string encryption,

            string endLSN,

            string endWal,

            Pulumi.Kubernetes.Types.Outputs.Postgresql.V1.BackupStatusEndpointca endpointCA,

            string endpointURL,

            string error,

            Pulumi.Kubernetes.Types.Outputs.Postgresql.V1.BackupStatusGooglecredentials googleCredentials,

            Pulumi.Kubernetes.Types.Outputs.Postgresql.V1.BackupStatusInstanceid instanceID,

            string phase,

            Pulumi.Kubernetes.Types.Outputs.Postgresql.V1.BackupStatusS3credentials s3Credentials,

            string serverName,

            string startedAt,

            string stoppedAt)
        {
            AzureCredentials = azureCredentials;
            BackupId = backupId;
            BackupName = backupName;
            BeginLSN = beginLSN;
            BeginWal = beginWal;
            CommandError = commandError;
            CommandOutput = commandOutput;
            DestinationPath = destinationPath;
            Encryption = encryption;
            EndLSN = endLSN;
            EndWal = endWal;
            EndpointCA = endpointCA;
            EndpointURL = endpointURL;
            Error = error;
            GoogleCredentials = googleCredentials;
            InstanceID = instanceID;
            Phase = phase;
            S3Credentials = s3Credentials;
            ServerName = serverName;
            StartedAt = startedAt;
            StoppedAt = stoppedAt;
        }
    }
}
