// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Postgresql.V1
{

    /// <summary>
    /// InstanceReportedState describes the last reported state of an instance during a reconciliation loop
    /// </summary>
    [OutputType]
    public sealed class ClusterStatusInstancesreportedstate
    {
        /// <summary>
        /// indicates if an instance is the primary one
        /// </summary>
        public readonly bool IsPrimary;
        /// <summary>
        /// indicates on which TimelineId the instance is
        /// </summary>
        public readonly int TimeLineID;

        [OutputConstructor]
        private ClusterStatusInstancesreportedstate(
            bool isPrimary,

            int timeLineID)
        {
            IsPrimary = isPrimary;
            TimeLineID = timeLineID;
        }
    }
}
