// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Postgresql.V1
{

    /// <summary>
    /// Bind+Search authentication configuration
    /// </summary>
    [OutputType]
    public sealed class ClusterSpecPostgresqlLdapBindsearchauth
    {
        /// <summary>
        /// Root DN to begin the user search
        /// </summary>
        public readonly string BaseDN;
        /// <summary>
        /// DN of the user to bind to the directory
        /// </summary>
        public readonly string BindDN;
        /// <summary>
        /// Secret with the password for the user to bind to the directory
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Postgresql.V1.ClusterSpecPostgresqlLdapBindsearchauthBindpassword BindPassword;
        /// <summary>
        /// Attribute to match against the username
        /// </summary>
        public readonly string SearchAttribute;
        /// <summary>
        /// Search filter to use when doing the search+bind authentication
        /// </summary>
        public readonly string SearchFilter;

        [OutputConstructor]
        private ClusterSpecPostgresqlLdapBindsearchauth(
            string baseDN,

            string bindDN,

            Pulumi.Kubernetes.Types.Outputs.Postgresql.V1.ClusterSpecPostgresqlLdapBindsearchauthBindpassword bindPassword,

            string searchAttribute,

            string searchFilter)
        {
            BaseDN = baseDN;
            BindDN = bindDN;
            BindPassword = bindPassword;
            SearchAttribute = searchAttribute;
            SearchFilter = searchFilter;
        }
    }
}
