// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Postgresql.V1
{

    /// <summary>
    /// The configuration for the backup of the WAL stream. When not defined, WAL files will be stored uncompressed and may be unencrypted in the object store, according to the bucket default policy.
    /// </summary>
    [OutputType]
    public sealed class ClusterSpecExternalclustersBarmanobjectstoreWal
    {
        /// <summary>
        /// Compress a WAL file before sending it to the object store. Available options are empty string (no compression, default), `gzip`, `bzip2` or `snappy`.
        /// </summary>
        public readonly string Compression;
        /// <summary>
        /// Whenever to force the encryption of files (if the bucket is not already configured for that). Allowed options are empty string (use the bucket policy, default), `AES256` and `aws:kms`
        /// </summary>
        public readonly string Encryption;
        /// <summary>
        /// Number of WAL files to be either archived in parallel (when the PostgreSQL instance is archiving to a backup object store) or restored in parallel (when a PostgreSQL standby is fetching WAL files from a recovery object store). If not specified, WAL files will be processed one at a time. It accepts a positive integer as a value - with 1 being the minimum accepted value.
        /// </summary>
        public readonly int MaxParallel;

        [OutputConstructor]
        private ClusterSpecExternalclustersBarmanobjectstoreWal(
            string compression,

            string encryption,

            int maxParallel)
        {
            Compression = compression;
            Encryption = encryption;
            MaxParallel = maxParallel;
        }
    }
}
