// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Postgresql.V1
{

    /// <summary>
    /// By default, the recovery process applies all the available WAL files in the archive (full recovery). However, you can also end the recovery as soon as a consistent state is reached or recover to a point-in-time (PITR) by specifying a `RecoveryTarget` object, as expected by PostgreSQL (i.e., timestamp, transaction Id, LSN, ...). More info: https://www.postgresql.org/docs/current/runtime-config-wal.html#RUNTIME-CONFIG-WAL-RECOVERY-TARGET
    /// </summary>
    [OutputType]
    public sealed class ClusterSpecBootstrapRecoveryRecoverytarget
    {
        /// <summary>
        /// The ID of the backup from which to start the recovery process. If empty (default) the operator will automatically detect the backup based on targetTime or targetLSN if specified. Otherwise use the latest available backup in chronological order.
        /// </summary>
        public readonly string BackupID;
        /// <summary>
        /// Set the target to be exclusive (defaults to true)
        /// </summary>
        public readonly bool Exclusive;
        /// <summary>
        /// End recovery as soon as a consistent state is reached
        /// </summary>
        public readonly bool TargetImmediate;
        /// <summary>
        /// The target LSN (Log Sequence Number)
        /// </summary>
        public readonly string TargetLSN;
        /// <summary>
        /// The target name (to be previously created with `pg_create_restore_point`)
        /// </summary>
        public readonly string TargetName;
        /// <summary>
        /// The target timeline ("latest" or a positive integer)
        /// </summary>
        public readonly string TargetTLI;
        /// <summary>
        /// The target time as a timestamp in the RFC3339 standard
        /// </summary>
        public readonly string TargetTime;
        /// <summary>
        /// The target transaction ID
        /// </summary>
        public readonly string TargetXID;

        [OutputConstructor]
        private ClusterSpecBootstrapRecoveryRecoverytarget(
            string backupID,

            bool exclusive,

            bool targetImmediate,

            string targetLSN,

            string targetName,

            string targetTLI,

            string targetTime,

            string targetXID)
        {
            BackupID = backupID;
            Exclusive = exclusive;
            TargetImmediate = targetImmediate;
            TargetLSN = targetLSN;
            TargetName = targetName;
            TargetTLI = targetTLI;
            TargetTime = targetTime;
            TargetXID = targetXID;
        }
    }
}
