// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Postgresql.V1
{

    /// <summary>
    /// The list of resource versions of the configmaps, managed by the operator. Every change here is done in the interest of the instance manager, which will refresh the configmap data
    /// </summary>
    [OutputType]
    public sealed class ClusterStatusConfigmapresourceversion
    {
        /// <summary>
        /// A map with the versions of all the config maps used to pass metrics. Map keys are the config map names, map values are the versions
        /// </summary>
        public readonly ImmutableDictionary<string, string> Metrics;

        [OutputConstructor]
        private ClusterStatusConfigmapresourceversion(ImmutableDictionary<string, string> metrics)
        {
            Metrics = metrics;
        }
    }
}
