// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Postgresql.V1
{

    /// <summary>
    /// Instructions to bootstrap this cluster
    /// </summary>
    [OutputType]
    public sealed class ClusterSpecBootstrap
    {
        /// <summary>
        /// Bootstrap the cluster via initdb
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Postgresql.V1.ClusterSpecBootstrapInitdb Initdb;
        /// <summary>
        /// Bootstrap the cluster taking a physical backup of another compatible PostgreSQL instance
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Postgresql.V1.ClusterSpecBootstrapPg_basebackup Pg_basebackup;
        /// <summary>
        /// Bootstrap the cluster from a backup
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Postgresql.V1.ClusterSpecBootstrapRecovery Recovery;

        [OutputConstructor]
        private ClusterSpecBootstrap(
            Pulumi.Kubernetes.Types.Outputs.Postgresql.V1.ClusterSpecBootstrapInitdb initdb,

            Pulumi.Kubernetes.Types.Outputs.Postgresql.V1.ClusterSpecBootstrapPg_basebackup pg_basebackup,

            Pulumi.Kubernetes.Types.Outputs.Postgresql.V1.ClusterSpecBootstrapRecovery recovery)
        {
            Initdb = initdb;
            Pg_basebackup = pg_basebackup;
            Recovery = recovery;
        }
    }
}
