// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Postgresql.V1
{

    /// <summary>
    /// The version of the secrets used by PgBouncer
    /// </summary>
    [OutputType]
    public sealed class PoolerStatusSecretsPgbouncersecrets
    {
        /// <summary>
        /// The auth query secret version
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Postgresql.V1.PoolerStatusSecretsPgbouncersecretsAuthquery AuthQuery;

        [OutputConstructor]
        private PoolerStatusSecretsPgbouncersecrets(Pulumi.Kubernetes.Types.Outputs.Postgresql.V1.PoolerStatusSecretsPgbouncersecretsAuthquery authQuery)
        {
            AuthQuery = authQuery;
        }
    }
}
