// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

namespace Pulumi.Kubernetes.Types.Inputs.Seaweed.V1
{

    /// <summary>
    /// The weights of all of the matched WeightedPodAffinityTerm fields are added per-node to find the most preferred node(s)
    /// </summary>
    public class SeaweedSpecFilerAffinityPodantiaffinityPreferredduringschedulingignoredduringexecutionArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Required. A pod affinity term, associated with the corresponding weight.
        /// </summary>
        [Input("podAffinityTerm", required: true)]
        public Input<Pulumi.Kubernetes.Types.Inputs.Seaweed.V1.SeaweedSpecFilerAffinityPodantiaffinityPreferredduringschedulingignoredduringexecutionPodaffinitytermArgs> PodAffinityTerm { get; set; } = null!;

        /// <summary>
        /// weight associated with matching the corresponding podAffinityTerm, in the range 1-100.
        /// </summary>
        [Input("weight", required: true)]
        public Input<int> Weight { get; set; } = null!;

        public SeaweedSpecFilerAffinityPodantiaffinityPreferredduringschedulingignoredduringexecutionArgs()
        {
        }
        public static new SeaweedSpecFilerAffinityPodantiaffinityPreferredduringschedulingignoredduringexecutionArgs Empty => new SeaweedSpecFilerAffinityPodantiaffinityPreferredduringschedulingignoredduringexecutionArgs();
    }
}
