// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

namespace Pulumi.Kubernetes.Types.Inputs.Seaweed.V1
{

    /// <summary>
    /// Source for the environment variable's value. Cannot be used if value is not empty.
    /// </summary>
    public class SeaweedSpecVolumeEnvValuefromArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Selects a key of a ConfigMap.
        /// </summary>
        [Input("configMapKeyRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Seaweed.V1.SeaweedSpecVolumeEnvValuefromConfigmapkeyrefArgs>? ConfigMapKeyRef { get; set; }

        /// <summary>
        /// Selects a field of the pod: supports metadata.name, metadata.namespace, metadata.labels, metadata.annotations, spec.nodeName, spec.serviceAccountName, status.hostIP, status.podIP, status.podIPs.
        /// </summary>
        [Input("fieldRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Seaweed.V1.SeaweedSpecVolumeEnvValuefromFieldrefArgs>? FieldRef { get; set; }

        /// <summary>
        /// Selects a resource of the container: only resources limits and requests (limits.cpu, limits.memory, limits.ephemeral-storage, requests.cpu, requests.memory and requests.ephemeral-storage) are currently supported.
        /// </summary>
        [Input("resourceFieldRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Seaweed.V1.SeaweedSpecVolumeEnvValuefromResourcefieldrefArgs>? ResourceFieldRef { get; set; }

        /// <summary>
        /// Selects a key of a secret in the pod's namespace
        /// </summary>
        [Input("secretKeyRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Seaweed.V1.SeaweedSpecVolumeEnvValuefromSecretkeyrefArgs>? SecretKeyRef { get; set; }

        public SeaweedSpecVolumeEnvValuefromArgs()
        {
        }
        public static new SeaweedSpecVolumeEnvValuefromArgs Empty => new SeaweedSpecVolumeEnvValuefromArgs();
    }
}
