// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Fluentbit.V1Alpha2
{

    /// <summary>
    /// InputSpec defines the desired state of ClusterInput
    /// </summary>
    public class ClusterInputSpecArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// A user friendly alias name for this input plugin. Used in metrics for distinction of each configured input.
        /// </summary>
        [Input("alias")]
        public Input<string>? Alias { get; set; }

        /// <summary>
        /// CustomPlugin defines Custom Input configuration.
        /// </summary>
        [Input("customPlugin")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Fluentbit.V1Alpha2.ClusterInputSpecCustompluginArgs>? CustomPlugin { get; set; }

        /// <summary>
        /// Dummy defines Dummy Input configuration.
        /// </summary>
        [Input("dummy")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Fluentbit.V1Alpha2.ClusterInputSpecDummyArgs>? Dummy { get; set; }

        /// <summary>
        /// FluentBitMetrics defines Fluent Bit Metrics Input configuration.
        /// </summary>
        [Input("fluentBitMetrics")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Fluentbit.V1Alpha2.ClusterInputSpecFluentbitmetricsArgs>? FluentBitMetrics { get; set; }

        /// <summary>
        /// NodeExporterMetrics defines Node Exporter Metrics Input configuration.
        /// </summary>
        [Input("nodeExporterMetrics")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Fluentbit.V1Alpha2.ClusterInputSpecNodeexportermetricsArgs>? NodeExporterMetrics { get; set; }

        /// <summary>
        /// PrometheusScrapeMetrics  defines Prometheus Scrape Metrics Input configuration.
        /// </summary>
        [Input("prometheusScrapeMetrics")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Fluentbit.V1Alpha2.ClusterInputSpecPrometheusscrapemetricsArgs>? PrometheusScrapeMetrics { get; set; }

        /// <summary>
        /// Systemd defines Systemd Input configuration.
        /// </summary>
        [Input("systemd")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Fluentbit.V1Alpha2.ClusterInputSpecSystemdArgs>? Systemd { get; set; }

        /// <summary>
        /// Tail defines Tail Input configuration.
        /// </summary>
        [Input("tail")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Fluentbit.V1Alpha2.ClusterInputSpecTailArgs>? Tail { get; set; }

        public ClusterInputSpecArgs()
        {
        }
        public static new ClusterInputSpecArgs Empty => new ClusterInputSpecArgs();
    }
}
