// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Fluentbit.V1Alpha2
{

    /// <summary>
    /// PrometheusRemoteWrite_types defines Prometheus Remote Write configuration.
    /// </summary>
    public class ClusterOutputSpecPrometheusremotewriteArgs : global::Pulumi.ResourceArgs
    {
        [Input("addLabels")]
        private InputMap<string>? _addLabels;

        /// <summary>
        /// This allows you to add custom labels to all metrics exposed through the prometheus exporter. You may have multiple of these fields
        /// </summary>
        public InputMap<string> AddLabels
        {
            get => _addLabels ?? (_addLabels = new InputMap<string>());
            set => _addLabels = value;
        }

        [Input("headers")]
        private InputMap<string>? _headers;

        /// <summary>
        /// Add a HTTP header key/value pair. Multiple headers can be set.
        /// </summary>
        public InputMap<string> Headers
        {
            get => _headers ?? (_headers = new InputMap<string>());
            set => _headers = value;
        }

        /// <summary>
        /// IP address or hostname of the target HTTP Server, default: 127.0.0.1
        /// </summary>
        [Input("host", required: true)]
        public Input<string> Host { get; set; } = null!;

        /// <summary>
        /// Basic Auth Password. Requires HTTP_user to be se
        /// </summary>
        [Input("httpPasswd")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Fluentbit.V1Alpha2.ClusterOutputSpecPrometheusremotewriteHttppasswdArgs>? HttpPasswd { get; set; }

        /// <summary>
        /// Basic Auth Username
        /// </summary>
        [Input("httpUser")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Fluentbit.V1Alpha2.ClusterOutputSpecPrometheusremotewriteHttpuserArgs>? HttpUser { get; set; }

        /// <summary>
        /// Log the response payload within the Fluent Bit log,default: false
        /// </summary>
        [Input("logResponsePayload")]
        public Input<bool>? LogResponsePayload { get; set; }

        /// <summary>
        /// TCP port of the target HTTP Serveri, default:80
        /// </summary>
        [Input("port")]
        public Input<int>? Port { get; set; }

        /// <summary>
        /// Specify an HTTP Proxy. The expected format of this value is http://HOST:PORT.
        /// </summary>
        [Input("proxy")]
        public Input<string>? Proxy { get; set; }

        /// <summary>
        /// Fluent Bit provides integrated support for Transport Layer Security (TLS) and it predecessor Secure Sockets Layer (SSL) respectively.
        /// </summary>
        [Input("tls")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Fluentbit.V1Alpha2.ClusterOutputSpecPrometheusremotewriteTlsArgs>? Tls { get; set; }

        /// <summary>
        /// Specify an optional HTTP URI for the target web server, e.g: /something ,default: /
        /// </summary>
        [Input("uri")]
        public Input<string>? Uri { get; set; }

        /// <summary>
        /// Enables dedicated thread(s) for this output. Default value is set since version 1.8.13. For previous versions is 0,default : 2
        /// </summary>
        [Input("workers")]
        public Input<int>? Workers { get; set; }

        public ClusterOutputSpecPrometheusremotewriteArgs()
        {
        }
        public static new ClusterOutputSpecPrometheusremotewriteArgs Empty => new ClusterOutputSpecPrometheusremotewriteArgs();
    }
}
