// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Fluentbit.V1Alpha2
{

    /// <summary>
    /// Dummy defines Dummy Input configuration.
    /// </summary>
    public class ClusterInputSpecDummyArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Dummy JSON record.
        /// </summary>
        [Input("dummy")]
        public Input<string>? Dummy { get; set; }

        /// <summary>
        /// Events number generated per second.
        /// </summary>
        [Input("rate")]
        public Input<int>? Rate { get; set; }

        /// <summary>
        /// Sample events to generate.
        /// </summary>
        [Input("samples")]
        public Input<int>? Samples { get; set; }

        /// <summary>
        /// Tag name associated to all records comming from this plugin.
        /// </summary>
        [Input("tag")]
        public Input<string>? Tag { get; set; }

        public ClusterInputSpecDummyArgs()
        {
        }
        public static new ClusterInputSpecDummyArgs Empty => new ClusterInputSpecDummyArgs();
    }
}
