// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Fluentbit.V1Alpha2
{

    /// <summary>
    /// Basic Auth Username
    /// </summary>
    public class ClusterOutputSpecHttpHttpuserArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// ValueSource defines how to find a value's key.
        /// </summary>
        [Input("valueFrom")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Fluentbit.V1Alpha2.ClusterOutputSpecHttpHttpuserValuefromArgs>? ValueFrom { get; set; }

        public ClusterOutputSpecHttpHttpuserArgs()
        {
        }
        public static new ClusterOutputSpecHttpHttpuserArgs Empty => new ClusterOutputSpecHttpHttpuserArgs();
    }
}
