// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Fluentbit.V1Alpha2
{

    /// <summary>
    /// Specify the username to present to a Fluentd server that enables user_auth.
    /// </summary>
    public class ClusterOutputSpecForwardUsernameArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// ValueSource defines how to find a value's key.
        /// </summary>
        [Input("valueFrom")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Fluentbit.V1Alpha2.ClusterOutputSpecForwardUsernameValuefromArgs>? ValueFrom { get; set; }

        public ClusterOutputSpecForwardUsernameArgs()
        {
        }
        public static new ClusterOutputSpecForwardUsernameArgs Empty => new ClusterOutputSpecForwardUsernameArgs();
    }
}
