// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Fluentbit.V1Alpha2
{

    /// <summary>
    /// Aws defines a Aws configuration.
    /// </summary>
    public class ClusterFilterSpecFiltersAwsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The account ID for current EC2 instance.Default is false.
        /// </summary>
        [Input("accountID")]
        public Input<bool>? AccountID { get; set; }

        /// <summary>
        /// Alias for the plugin
        /// </summary>
        [Input("alias")]
        public Input<string>? Alias { get; set; }

        /// <summary>
        /// The EC2 instance image id.Default is false.
        /// </summary>
        [Input("amiID")]
        public Input<bool>? AmiID { get; set; }

        /// <summary>
        /// The availability zone; for example, "us-east-1a". Default is true.
        /// </summary>
        [Input("az")]
        public Input<bool>? Az { get; set; }

        /// <summary>
        /// The EC2 instance ID.Default is true.
        /// </summary>
        [Input("ec2InstanceID")]
        public Input<bool>? Ec2InstanceID { get; set; }

        /// <summary>
        /// The EC2 instance type.Default is false.
        /// </summary>
        [Input("ec2InstanceType")]
        public Input<bool>? Ec2InstanceType { get; set; }

        /// <summary>
        /// The hostname for current EC2 instance.Default is false.
        /// </summary>
        [Input("hostName")]
        public Input<bool>? HostName { get; set; }

        /// <summary>
        /// Specify which version of the instance metadata service to use. Valid values are 'v1' or 'v2'.
        /// </summary>
        [Input("imdsVersion")]
        public Input<string>? ImdsVersion { get; set; }

        /// <summary>
        /// The EC2 instance private ip.Default is false.
        /// </summary>
        [Input("privateIP")]
        public Input<bool>? PrivateIP { get; set; }

        /// <summary>
        /// RetryLimit describes how many times fluent-bit should retry to send data to a specific output. If set to false fluent-bit will try indefinetly. If set to any integer N&gt;0 it will try at most N+1 times. Leading zeros are not allowed (values such as 007, 0150, 01 do not work). If this property is not defined fluent-bit will use the default value: 1.
        /// </summary>
        [Input("retryLimit")]
        public Input<string>? RetryLimit { get; set; }

        /// <summary>
        /// The VPC ID for current EC2 instance.Default is false.
        /// </summary>
        [Input("vpcID")]
        public Input<bool>? VpcID { get; set; }

        public ClusterFilterSpecFiltersAwsArgs()
        {
        }
        public static new ClusterFilterSpecFiltersAwsArgs Empty => new ClusterFilterSpecFiltersAwsArgs();
    }
}
