// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Fluentbit.V1Alpha2
{

    public class ClusterFilterSpecFiltersArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Aws defines a Aws configuration.
        /// </summary>
        [Input("aws")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Fluentbit.V1Alpha2.ClusterFilterSpecFiltersAwsArgs>? Aws { get; set; }

        /// <summary>
        /// CustomPlugin defines a Custom plugin configuration.
        /// </summary>
        [Input("customPlugin")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Fluentbit.V1Alpha2.ClusterFilterSpecFiltersCustompluginArgs>? CustomPlugin { get; set; }

        /// <summary>
        /// Grep defines Grep Filter configuration.
        /// </summary>
        [Input("grep")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Fluentbit.V1Alpha2.ClusterFilterSpecFiltersGrepArgs>? Grep { get; set; }

        /// <summary>
        /// Kubernetes defines Kubernetes Filter configuration.
        /// </summary>
        [Input("kubernetes")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Fluentbit.V1Alpha2.ClusterFilterSpecFiltersKubernetesArgs>? Kubernetes { get; set; }

        /// <summary>
        /// Lua defines Lua Filter configuration.
        /// </summary>
        [Input("lua")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Fluentbit.V1Alpha2.ClusterFilterSpecFiltersLuaArgs>? Lua { get; set; }

        /// <summary>
        /// Modify defines Modify Filter configuration.
        /// </summary>
        [Input("modify")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Fluentbit.V1Alpha2.ClusterFilterSpecFiltersModifyArgs>? Modify { get; set; }

        /// <summary>
        /// Multiline defines a Multiline configuration.
        /// </summary>
        [Input("multiline")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Fluentbit.V1Alpha2.ClusterFilterSpecFiltersMultilineArgs>? Multiline { get; set; }

        /// <summary>
        /// Nest defines Nest Filter configuration.
        /// </summary>
        [Input("nest")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Fluentbit.V1Alpha2.ClusterFilterSpecFiltersNestArgs>? Nest { get; set; }

        /// <summary>
        /// Parser defines Parser Filter configuration.
        /// </summary>
        [Input("parser")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Fluentbit.V1Alpha2.ClusterFilterSpecFiltersParserArgs>? Parser { get; set; }

        /// <summary>
        /// RecordModifier defines Record Modifier Filter configuration.
        /// </summary>
        [Input("recordModifier")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Fluentbit.V1Alpha2.ClusterFilterSpecFiltersRecordmodifierArgs>? RecordModifier { get; set; }

        /// <summary>
        /// RewriteTag defines a RewriteTag configuration.
        /// </summary>
        [Input("rewriteTag")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Fluentbit.V1Alpha2.ClusterFilterSpecFiltersRewritetagArgs>? RewriteTag { get; set; }

        /// <summary>
        /// Throttle defines a Throttle configuration.
        /// </summary>
        [Input("throttle")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Fluentbit.V1Alpha2.ClusterFilterSpecFiltersThrottleArgs>? Throttle { get; set; }

        public ClusterFilterSpecFiltersArgs()
        {
        }
        public static new ClusterFilterSpecFiltersArgs Empty => new ClusterFilterSpecFiltersArgs();
    }
}
