// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Fluentbit.V1Alpha2
{

    /// <summary>
    /// Optional username credential for Elastic X-Pack access
    /// </summary>
    public class ClusterOutputSpecEsHttpuserArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// ValueSource defines how to find a value's key.
        /// </summary>
        [Input("valueFrom")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Fluentbit.V1Alpha2.ClusterOutputSpecEsHttpuserValuefromArgs>? ValueFrom { get; set; }

        public ClusterOutputSpecEsHttpuserArgs()
        {
        }
        public static new ClusterOutputSpecEsHttpuserArgs Empty => new ClusterOutputSpecEsHttpuserArgs();
    }
}
