// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Fluentbit.V1Alpha2
{

    /// <summary>
    /// NodeExporterMetrics defines Node Exporter Metrics Input configuration.
    /// </summary>
    [OutputType]
    public sealed class ClusterInputSpecNodeexportermetrics
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.Fluentbit.V1Alpha2.ClusterInputSpecNodeexportermetricsPath Path;
        /// <summary>
        /// The rate at which metrics are collected from the host operating system, default is 5 seconds.
        /// </summary>
        public readonly string ScrapeInterval;
        /// <summary>
        /// Tag name associated to all records comming from this plugin.
        /// </summary>
        public readonly string Tag;

        [OutputConstructor]
        private ClusterInputSpecNodeexportermetrics(
            Pulumi.Kubernetes.Types.Outputs.Fluentbit.V1Alpha2.ClusterInputSpecNodeexportermetricsPath path,

            string scrapeInterval,

            string tag)
        {
            Path = path;
            ScrapeInterval = scrapeInterval;
            Tag = tag;
        }
    }
}
