// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Fluentbit.V1Alpha2
{

    /// <summary>
    /// Loki defines Loki Output configuration.
    /// </summary>
    [OutputType]
    public sealed class ClusterOutputSpecLoki
    {
        /// <summary>
        /// If set to true, it will add all Kubernetes labels to the Stream labels.
        /// </summary>
        public readonly string AutoKubernetesLabels;
        /// <summary>
        /// Loki hostname or IP address.
        /// </summary>
        public readonly string Host;
        /// <summary>
        /// Password for user defined in HTTP_User Set HTTP basic authentication password
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Fluentbit.V1Alpha2.ClusterOutputSpecLokiHttppassword HttpPassword;
        /// <summary>
        /// Set HTTP basic authentication user name.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Fluentbit.V1Alpha2.ClusterOutputSpecLokiHttpuser HttpUser;
        /// <summary>
        /// Optional list of record keys that will be placed as stream labels. This configuration property is for records key only.
        /// </summary>
        public readonly ImmutableArray<string> LabelKeys;
        /// <summary>
        /// Stream labels for API request. It can be multiple comma separated of strings specifying  key=value pairs. In addition to fixed parameters, it also allows to add custom record keys (similar to label_keys property).
        /// </summary>
        public readonly ImmutableArray<string> Labels;
        /// <summary>
        /// Format to use when flattening the record to a log line. Valid values are json or key_value. If set to json,  the log line sent to Loki will be the Fluent Bit record dumped as JSON. If set to key_value, the log line will be each item in the record concatenated together (separated by a single space) in the format.
        /// </summary>
        public readonly string LineFormat;
        /// <summary>
        /// Loki TCP port
        /// </summary>
        public readonly int Port;
        /// <summary>
        /// Tenant ID used by default to push logs to Loki. If omitted or empty it assumes Loki is running in single-tenant mode and no X-Scope-OrgID header is sent.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Fluentbit.V1Alpha2.ClusterOutputSpecLokiTenantid TenantID;
        /// <summary>
        /// Fluent Bit provides integrated support for Transport Layer Security (TLS) and it predecessor Secure Sockets Layer (SSL) respectively.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Fluentbit.V1Alpha2.ClusterOutputSpecLokiTls Tls;

        [OutputConstructor]
        private ClusterOutputSpecLoki(
            string autoKubernetesLabels,

            string host,

            Pulumi.Kubernetes.Types.Outputs.Fluentbit.V1Alpha2.ClusterOutputSpecLokiHttppassword httpPassword,

            Pulumi.Kubernetes.Types.Outputs.Fluentbit.V1Alpha2.ClusterOutputSpecLokiHttpuser httpUser,

            ImmutableArray<string> labelKeys,

            ImmutableArray<string> labels,

            string lineFormat,

            int port,

            Pulumi.Kubernetes.Types.Outputs.Fluentbit.V1Alpha2.ClusterOutputSpecLokiTenantid tenantID,

            Pulumi.Kubernetes.Types.Outputs.Fluentbit.V1Alpha2.ClusterOutputSpecLokiTls tls)
        {
            AutoKubernetesLabels = autoKubernetesLabels;
            Host = host;
            HttpPassword = httpPassword;
            HttpUser = httpUser;
            LabelKeys = labelKeys;
            Labels = labels;
            LineFormat = lineFormat;
            Port = port;
            TenantID = tenantID;
            Tls = tls;
        }
    }
}
