// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Fluentbit.V1Alpha2
{

    /// <summary>
    /// CloudWatch defines CloudWatch Output Configuration
    /// </summary>
    [OutputType]
    public sealed class ClusterOutputSpecCloudwatch
    {
        /// <summary>
        /// Automatically create the log group. Defaults to False.
        /// </summary>
        public readonly bool AutoCreateGroup;
        /// <summary>
        /// Automatically retry failed requests to CloudWatch once. Defaults to True.
        /// </summary>
        public readonly bool AutoRetryRequests;
        /// <summary>
        /// Custom endpoint for CloudWatch logs API
        /// </summary>
        public readonly string Endpoint;
        /// <summary>
        /// Specify an external ID for the STS API.
        /// </summary>
        public readonly string ExternalID;
        /// <summary>
        /// Optional parameter to tell CloudWatch the format of the data
        /// </summary>
        public readonly string LogFormat;
        /// <summary>
        /// Name of Cloudwatch Log Group to send log records to
        /// </summary>
        public readonly string LogGroupName;
        /// <summary>
        /// Template for Log Group name, overrides LogGroupName if set.
        /// </summary>
        public readonly string LogGroupTemplate;
        /// <summary>
        /// If set, only the value of the key will be sent to CloudWatch
        /// </summary>
        public readonly string LogKey;
        /// <summary>
        /// Number of days logs are retained for
        /// </summary>
        public readonly int LogRetentionDays;
        /// <summary>
        /// The name of the CloudWatch Log Stream to send log records to
        /// </summary>
        public readonly string LogStreamName;
        /// <summary>
        /// Prefix for the Log Stream name. Not compatible with LogStreamName setting
        /// </summary>
        public readonly string LogStreamPrefix;
        /// <summary>
        /// Template for Log Stream name. Overrides LogStreamPrefix and LogStreamName if set.
        /// </summary>
        public readonly string LogStreamTemplate;
        /// <summary>
        /// Optional lists of lists for dimension keys to be added to all metrics. Use comma separated strings for one list of dimensions and semicolon separated strings for list of lists dimensions.
        /// </summary>
        public readonly string MetricDimensions;
        /// <summary>
        /// Optional string to represent the CloudWatch namespace.
        /// </summary>
        public readonly string MetricNamespace;
        /// <summary>
        /// AWS Region
        /// </summary>
        public readonly string Region;
        /// <summary>
        /// Role ARN to use for cross-account access
        /// </summary>
        public readonly string RoleArn;
        /// <summary>
        /// Specify a custom STS endpoint for the AWS STS API
        /// </summary>
        public readonly string StsEndpoint;

        [OutputConstructor]
        private ClusterOutputSpecCloudwatch(
            bool autoCreateGroup,

            bool autoRetryRequests,

            string endpoint,

            string externalID,

            string logFormat,

            string logGroupName,

            string logGroupTemplate,

            string logKey,

            int logRetentionDays,

            string logStreamName,

            string logStreamPrefix,

            string logStreamTemplate,

            string metricDimensions,

            string metricNamespace,

            string region,

            string roleArn,

            string stsEndpoint)
        {
            AutoCreateGroup = autoCreateGroup;
            AutoRetryRequests = autoRetryRequests;
            Endpoint = endpoint;
            ExternalID = externalID;
            LogFormat = logFormat;
            LogGroupName = logGroupName;
            LogGroupTemplate = logGroupTemplate;
            LogKey = logKey;
            LogRetentionDays = logRetentionDays;
            LogStreamName = logStreamName;
            LogStreamPrefix = logStreamPrefix;
            LogStreamTemplate = logStreamTemplate;
            MetricDimensions = metricDimensions;
            MetricNamespace = metricNamespace;
            Region = region;
            RoleArn = roleArn;
            StsEndpoint = stsEndpoint;
        }
    }
}
