// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Fluentbit.V1Alpha2
{

    /// <summary>
    /// Aws defines a Aws configuration.
    /// </summary>
    [OutputType]
    public sealed class ClusterFilterSpecFiltersAws
    {
        /// <summary>
        /// The account ID for current EC2 instance.Default is false.
        /// </summary>
        public readonly bool AccountID;
        /// <summary>
        /// Alias for the plugin
        /// </summary>
        public readonly string Alias;
        /// <summary>
        /// The EC2 instance image id.Default is false.
        /// </summary>
        public readonly bool AmiID;
        /// <summary>
        /// The availability zone; for example, "us-east-1a". Default is true.
        /// </summary>
        public readonly bool Az;
        /// <summary>
        /// The EC2 instance ID.Default is true.
        /// </summary>
        public readonly bool Ec2InstanceID;
        /// <summary>
        /// The EC2 instance type.Default is false.
        /// </summary>
        public readonly bool Ec2InstanceType;
        /// <summary>
        /// The hostname for current EC2 instance.Default is false.
        /// </summary>
        public readonly bool HostName;
        /// <summary>
        /// Specify which version of the instance metadata service to use. Valid values are 'v1' or 'v2'.
        /// </summary>
        public readonly string ImdsVersion;
        /// <summary>
        /// The EC2 instance private ip.Default is false.
        /// </summary>
        public readonly bool PrivateIP;
        /// <summary>
        /// RetryLimit describes how many times fluent-bit should retry to send data to a specific output. If set to false fluent-bit will try indefinetly. If set to any integer N&gt;0 it will try at most N+1 times. Leading zeros are not allowed (values such as 007, 0150, 01 do not work). If this property is not defined fluent-bit will use the default value: 1.
        /// </summary>
        public readonly string RetryLimit;
        /// <summary>
        /// The VPC ID for current EC2 instance.Default is false.
        /// </summary>
        public readonly bool VpcID;

        [OutputConstructor]
        private ClusterFilterSpecFiltersAws(
            bool accountID,

            string alias,

            bool amiID,

            bool az,

            bool ec2InstanceID,

            bool ec2InstanceType,

            bool hostName,

            string imdsVersion,

            bool privateIP,

            string retryLimit,

            bool vpcID)
        {
            AccountID = accountID;
            Alias = alias;
            AmiID = amiID;
            Az = az;
            Ec2InstanceID = ec2InstanceID;
            Ec2InstanceType = ec2InstanceType;
            HostName = hostName;
            ImdsVersion = imdsVersion;
            PrivateIP = privateIP;
            RetryLimit = retryLimit;
            VpcID = vpcID;
        }
    }
}
