// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Traefik.V1Alpha1
{

    /// <summary>
    /// PassTLSClientCert holds the pass TLS client cert middleware configuration. This middleware adds the selected data from the passed client TLS certificate to a header. More info: https://doc.traefik.io/traefik/v2.9/middlewares/http/passtlsclientcert/
    /// </summary>
    [OutputType]
    public sealed class MiddlewareSpecPasstlsclientcert
    {
        /// <summary>
        /// Info selects the specific client certificate details you want to add to the X-Forwarded-Tls-Client-Cert-Info header.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Traefik.V1Alpha1.MiddlewareSpecPasstlsclientcertInfo Info;
        /// <summary>
        /// PEM sets the X-Forwarded-Tls-Client-Cert header with the certificate.
        /// </summary>
        public readonly bool Pem;

        [OutputConstructor]
        private MiddlewareSpecPasstlsclientcert(
            Pulumi.Kubernetes.Types.Outputs.Traefik.V1Alpha1.MiddlewareSpecPasstlsclientcertInfo info,

            bool pem)
        {
            Info = info;
            Pem = pem;
        }
    }
}
