// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

namespace Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1
{

    /// <summary>
    /// AddPrefix holds the add prefix middleware configuration. This middleware updates the path of a request before forwarding it. More info: https://doc.traefik.io/traefik/v2.9/middlewares/http/addprefix/
    /// </summary>
    public class MiddlewareSpecAddprefixArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Prefix is the string to add before the current path in the requested URL. It should include a leading slash (/).
        /// </summary>
        [Input("prefix")]
        public Input<string>? Prefix { get; set; }

        public MiddlewareSpecAddprefixArgs()
        {
        }
        public static new MiddlewareSpecAddprefixArgs Empty => new MiddlewareSpecAddprefixArgs();
    }
}
