// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Monitoring.V1
{

    /// <summary>
    /// PodMetricsEndpoint defines a scrapeable endpoint of a Kubernetes Pod serving Prometheus metrics.
    /// </summary>
    public class PodMonitorSpecPodmetricsendpointsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Authorization section for this endpoint
        /// </summary>
        [Input("authorization")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Monitoring.V1.PodMonitorSpecPodmetricsendpointsAuthorizationArgs>? Authorization { get; set; }

        /// <summary>
        /// BasicAuth allow an endpoint to authenticate over basic authentication. More info: https://prometheus.io/docs/operating/configuration/#endpoint
        /// </summary>
        [Input("basicAuth")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Monitoring.V1.PodMonitorSpecPodmetricsendpointsBasicauthArgs>? BasicAuth { get; set; }

        /// <summary>
        /// Secret to mount to read bearer token for scraping targets. The secret needs to be in the same namespace as the pod monitor and accessible by the Prometheus Operator.
        /// </summary>
        [Input("bearerTokenSecret")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Monitoring.V1.PodMonitorSpecPodmetricsendpointsBearertokensecretArgs>? BearerTokenSecret { get; set; }

        /// <summary>
        /// Whether to enable HTTP2.
        /// </summary>
        [Input("enableHttp2")]
        public Input<bool>? EnableHttp2 { get; set; }

        /// <summary>
        /// Drop pods that are not running. (Failed, Succeeded). Enabled by default. More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-phase
        /// </summary>
        [Input("filterRunning")]
        public Input<bool>? FilterRunning { get; set; }

        /// <summary>
        /// FollowRedirects configures whether scrape requests follow HTTP 3xx redirects.
        /// </summary>
        [Input("followRedirects")]
        public Input<bool>? FollowRedirects { get; set; }

        /// <summary>
        /// HonorLabels chooses the metric's labels on collisions with target labels.
        /// </summary>
        [Input("honorLabels")]
        public Input<bool>? HonorLabels { get; set; }

        /// <summary>
        /// HonorTimestamps controls whether Prometheus respects the timestamps present in scraped data.
        /// </summary>
        [Input("honorTimestamps")]
        public Input<bool>? HonorTimestamps { get; set; }

        /// <summary>
        /// Interval at which metrics should be scraped If not specified Prometheus' global scrape interval is used.
        /// </summary>
        [Input("interval")]
        public Input<string>? Interval { get; set; }

        [Input("metricRelabelings")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Monitoring.V1.PodMonitorSpecPodmetricsendpointsMetricrelabelingsArgs>? _metricRelabelings;

        /// <summary>
        /// MetricRelabelConfigs to apply to samples before ingestion.
        /// </summary>
        public InputList<Pulumi.Kubernetes.Types.Inputs.Monitoring.V1.PodMonitorSpecPodmetricsendpointsMetricrelabelingsArgs> MetricRelabelings
        {
            get => _metricRelabelings ?? (_metricRelabelings = new InputList<Pulumi.Kubernetes.Types.Inputs.Monitoring.V1.PodMonitorSpecPodmetricsendpointsMetricrelabelingsArgs>());
            set => _metricRelabelings = value;
        }

        /// <summary>
        /// OAuth2 for the URL. Only valid in Prometheus versions 2.27.0 and newer.
        /// </summary>
        [Input("oauth2")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Monitoring.V1.PodMonitorSpecPodmetricsendpointsOauth2Args>? Oauth2 { get; set; }

        [Input("params")]
        private InputMap<ImmutableArray<string>>? _params;

        /// <summary>
        /// Optional HTTP URL parameters
        /// </summary>
        public InputMap<ImmutableArray<string>> Params
        {
            get => _params ?? (_params = new InputMap<ImmutableArray<string>>());
            set => _params = value;
        }

        /// <summary>
        /// HTTP path to scrape for metrics. If empty, Prometheus uses the default value (e.g. `/metrics`).
        /// </summary>
        [Input("path")]
        public Input<string>? Path { get; set; }

        /// <summary>
        /// Name of the pod port this endpoint refers to. Mutually exclusive with targetPort.
        /// </summary>
        [Input("port")]
        public Input<string>? Port { get; set; }

        /// <summary>
        /// ProxyURL eg http://proxyserver:2195 Directs scrapes to proxy through this endpoint.
        /// </summary>
        [Input("proxyUrl")]
        public Input<string>? ProxyUrl { get; set; }

        [Input("relabelings")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Monitoring.V1.PodMonitorSpecPodmetricsendpointsRelabelingsArgs>? _relabelings;

        /// <summary>
        /// RelabelConfigs to apply to samples before scraping. Prometheus Operator automatically adds relabelings for a few standard Kubernetes fields. The original scrape job's name is available via the `__tmp_prometheus_job_name` label. More info: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config
        /// </summary>
        public InputList<Pulumi.Kubernetes.Types.Inputs.Monitoring.V1.PodMonitorSpecPodmetricsendpointsRelabelingsArgs> Relabelings
        {
            get => _relabelings ?? (_relabelings = new InputList<Pulumi.Kubernetes.Types.Inputs.Monitoring.V1.PodMonitorSpecPodmetricsendpointsRelabelingsArgs>());
            set => _relabelings = value;
        }

        /// <summary>
        /// HTTP scheme to use for scraping.
        /// </summary>
        [Input("scheme")]
        public Input<string>? Scheme { get; set; }

        /// <summary>
        /// Timeout after which the scrape is ended If not specified, the Prometheus global scrape interval is used.
        /// </summary>
        [Input("scrapeTimeout")]
        public Input<string>? ScrapeTimeout { get; set; }

        /// <summary>
        /// Deprecated: Use 'port' instead.
        /// </summary>
        [Input("targetPort")]
        public InputUnion<int, string>? TargetPort { get; set; }

        /// <summary>
        /// TLS configuration to use when scraping the endpoint.
        /// </summary>
        [Input("tlsConfig")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Monitoring.V1.PodMonitorSpecPodmetricsendpointsTlsconfigArgs>? TlsConfig { get; set; }

        public PodMonitorSpecPodmetricsendpointsArgs()
        {
        }
        public static new PodMonitorSpecPodmetricsendpointsArgs Empty => new PodMonitorSpecPodmetricsendpointsArgs();
    }
}
