// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Monitoring.V1
{

    /// <summary>
    /// Rule describes an alerting or recording rule See Prometheus documentation: [alerting](https://www.prometheus.io/docs/prometheus/latest/configuration/alerting_rules/) or [recording](https://www.prometheus.io/docs/prometheus/latest/configuration/recording_rules/#recording-rules) rule
    /// </summary>
    public class PrometheusRuleSpecGroupsRulesArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Name of the alert. Must be a valid label value. Only one of `record` and `alert` must be set.
        /// </summary>
        [Input("alert")]
        public Input<string>? Alert { get; set; }

        [Input("annotations")]
        private InputMap<string>? _annotations;

        /// <summary>
        /// Annotations to add to each alert. Only valid for alerting rules.
        /// </summary>
        public InputMap<string> Annotations
        {
            get => _annotations ?? (_annotations = new InputMap<string>());
            set => _annotations = value;
        }

        /// <summary>
        /// PromQL expression to evaluate.
        /// </summary>
        [Input("expr", required: true)]
        public InputUnion<int, string> Expr { get; set; } = null!;

        /// <summary>
        /// Alerts are considered firing once they have been returned for this long.
        /// </summary>
        [Input("for")]
        public Input<string>? For { get; set; }

        [Input("labels")]
        private InputMap<string>? _labels;

        /// <summary>
        /// Labels to add or overwrite.
        /// </summary>
        public InputMap<string> Labels
        {
            get => _labels ?? (_labels = new InputMap<string>());
            set => _labels = value;
        }

        /// <summary>
        /// Name of the time series to output to. Must be a valid metric name. Only one of `record` and `alert` must be set.
        /// </summary>
        [Input("record")]
        public Input<string>? Record { get; set; }

        public PrometheusRuleSpecGroupsRulesArgs()
        {
        }
        public static new PrometheusRuleSpecGroupsRulesArgs Empty => new PrometheusRuleSpecGroupsRulesArgs();
    }
}
