// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Monitoring.V1
{

    /// <summary>
    /// RuleGroup is a list of sequentially evaluated recording and alerting rules.
    /// </summary>
    public class PrometheusRuleSpecGroupsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Interval determines how often rules in the group are evaluated.
        /// </summary>
        [Input("interval")]
        public Input<string>? Interval { get; set; }

        /// <summary>
        /// Name of the rule group.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// PartialResponseStrategy is only used by ThanosRuler and will be ignored by Prometheus instances. More info: https://github.com/thanos-io/thanos/blob/main/docs/components/rule.md#partial-response
        /// </summary>
        [Input("partial_response_strategy")]
        public Input<string>? Partial_response_strategy { get; set; }

        [Input("rules", required: true)]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Monitoring.V1.PrometheusRuleSpecGroupsRulesArgs>? _rules;

        /// <summary>
        /// List of alerting and recording rules.
        /// </summary>
        public InputList<Pulumi.Kubernetes.Types.Inputs.Monitoring.V1.PrometheusRuleSpecGroupsRulesArgs> Rules
        {
            get => _rules ?? (_rules = new InputList<Pulumi.Kubernetes.Types.Inputs.Monitoring.V1.PrometheusRuleSpecGroupsRulesArgs>());
            set => _rules = value;
        }

        public PrometheusRuleSpecGroupsArgs()
        {
        }
        public static new PrometheusRuleSpecGroupsArgs Empty => new PrometheusRuleSpecGroupsArgs();
    }
}
