// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

namespace Pulumi.Kubernetes.Types.Inputs.Monitoring.V1
{

    /// <summary>
    /// Authorization section for this endpoint
    /// </summary>
    public class ServiceMonitorSpecEndpointsAuthorizationArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The secret's key that contains the credentials of the request
        /// </summary>
        [Input("credentials")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Monitoring.V1.ServiceMonitorSpecEndpointsAuthorizationCredentialsArgs>? Credentials { get; set; }

        /// <summary>
        /// Set the authentication type. Defaults to Bearer, Basic will cause an error
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        public ServiceMonitorSpecEndpointsAuthorizationArgs()
        {
        }
        public static new ServiceMonitorSpecEndpointsAuthorizationArgs Empty => new ServiceMonitorSpecEndpointsAuthorizationArgs();
    }
}
