// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

namespace Pulumi.Kubernetes.Types.Inputs.Monitoring.V1
{

    /// <summary>
    /// Certificate authority used when verifying server certificates.
    /// </summary>
    public class ServiceMonitorSpecEndpointsTlsconfigCaArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// ConfigMap containing data to use for the targets.
        /// </summary>
        [Input("configMap")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Monitoring.V1.ServiceMonitorSpecEndpointsTlsconfigCaConfigmapArgs>? ConfigMap { get; set; }

        /// <summary>
        /// Secret containing data to use for the targets.
        /// </summary>
        [Input("secret")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Monitoring.V1.ServiceMonitorSpecEndpointsTlsconfigCaSecretArgs>? Secret { get; set; }

        public ServiceMonitorSpecEndpointsTlsconfigCaArgs()
        {
        }
        public static new ServiceMonitorSpecEndpointsTlsconfigCaArgs Empty => new ServiceMonitorSpecEndpointsTlsconfigCaArgs();
    }
}
