// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Vault.V1Alpha1
{

    public class VaultSpecUnsealconfigKubernetesArgs : global::Pulumi.ResourceArgs
    {
        [Input("secretName")]
        public Input<string>? SecretName { get; set; }

        [Input("secretNamespace")]
        public Input<string>? SecretNamespace { get; set; }

        public VaultSpecUnsealconfigKubernetesArgs()
        {
        }
        public static new VaultSpecUnsealconfigKubernetesArgs Empty => new VaultSpecUnsealconfigKubernetesArgs();
    }
}
