// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Vault.V1Alpha1
{

    public class VaultSpecVaultpodspecEphemeralcontainersEnvArgs : global::Pulumi.ResourceArgs
    {
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("value")]
        public Input<string>? Value { get; set; }

        [Input("valueFrom")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Vault.V1Alpha1.VaultSpecVaultpodspecEphemeralcontainersEnvValuefromArgs>? ValueFrom { get; set; }

        public VaultSpecVaultpodspecEphemeralcontainersEnvArgs()
        {
        }
        public static new VaultSpecVaultpodspecEphemeralcontainersEnvArgs Empty => new VaultSpecVaultpodspecEphemeralcontainersEnvArgs();
    }
}
