// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Vault.V1Alpha1
{

    public class VaultSpecArgs : global::Pulumi.ResourceArgs
    {
        [Input("affinity")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Vault.V1Alpha1.VaultSpecAffinityArgs>? Affinity { get; set; }

        [Input("annotations")]
        private InputMap<string>? _annotations;
        public InputMap<string> Annotations
        {
            get => _annotations ?? (_annotations = new InputMap<string>());
            set => _annotations = value;
        }

        [Input("bankVaultsImage")]
        public Input<string>? BankVaultsImage { get; set; }

        [Input("bankVaultsVolumeMounts")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Vault.V1Alpha1.VaultSpecBankvaultsvolumemountsArgs>? _bankVaultsVolumeMounts;
        public InputList<Pulumi.Kubernetes.Types.Inputs.Vault.V1Alpha1.VaultSpecBankvaultsvolumemountsArgs> BankVaultsVolumeMounts
        {
            get => _bankVaultsVolumeMounts ?? (_bankVaultsVolumeMounts = new InputList<Pulumi.Kubernetes.Types.Inputs.Vault.V1Alpha1.VaultSpecBankvaultsvolumemountsArgs>());
            set => _bankVaultsVolumeMounts = value;
        }

        [Input("caNamespaces")]
        private InputList<string>? _caNamespaces;
        public InputList<string> CaNamespaces
        {
            get => _caNamespaces ?? (_caNamespaces = new InputList<string>());
            set => _caNamespaces = value;
        }

        [Input("config", required: true)]
        private InputMap<object>? _config;
        public InputMap<object> Config
        {
            get => _config ?? (_config = new InputMap<object>());
            set => _config = value;
        }

        [Input("credentialsConfig")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Vault.V1Alpha1.VaultSpecCredentialsconfigArgs>? CredentialsConfig { get; set; }

        [Input("envsConfig")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Vault.V1Alpha1.VaultSpecEnvsconfigArgs>? _envsConfig;
        public InputList<Pulumi.Kubernetes.Types.Inputs.Vault.V1Alpha1.VaultSpecEnvsconfigArgs> EnvsConfig
        {
            get => _envsConfig ?? (_envsConfig = new InputList<Pulumi.Kubernetes.Types.Inputs.Vault.V1Alpha1.VaultSpecEnvsconfigArgs>());
            set => _envsConfig = value;
        }

        [Input("existingTlsSecretName")]
        public Input<string>? ExistingTlsSecretName { get; set; }

        [Input("externalConfig")]
        private InputMap<object>? _externalConfig;
        public InputMap<object> ExternalConfig
        {
            get => _externalConfig ?? (_externalConfig = new InputMap<object>());
            set => _externalConfig = value;
        }

        [Input("fluentdConfFile")]
        public Input<string>? FluentdConfFile { get; set; }

        [Input("fluentdConfLocation")]
        public Input<string>? FluentdConfLocation { get; set; }

        [Input("fluentdConfig")]
        public Input<string>? FluentdConfig { get; set; }

        [Input("fluentdEnabled")]
        public Input<bool>? FluentdEnabled { get; set; }

        [Input("fluentdImage")]
        public Input<string>? FluentdImage { get; set; }

        [Input("image")]
        public Input<string>? Image { get; set; }

        [Input("ingress")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Vault.V1Alpha1.VaultSpecIngressArgs>? Ingress { get; set; }

        [Input("istioEnabled")]
        public Input<bool>? IstioEnabled { get; set; }

        [Input("loadBalancerIP")]
        public Input<string>? LoadBalancerIP { get; set; }

        [Input("nodeAffinity")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Vault.V1Alpha1.VaultSpecNodeaffinityArgs>? NodeAffinity { get; set; }

        [Input("nodeSelector")]
        private InputMap<string>? _nodeSelector;
        public InputMap<string> NodeSelector
        {
            get => _nodeSelector ?? (_nodeSelector = new InputMap<string>());
            set => _nodeSelector = value;
        }

        [Input("podAntiAffinity")]
        public Input<string>? PodAntiAffinity { get; set; }

        [Input("raftLeaderAddress")]
        public Input<string>? RaftLeaderAddress { get; set; }

        [Input("resources")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Vault.V1Alpha1.VaultSpecResourcesArgs>? Resources { get; set; }

        [Input("securityContext")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Vault.V1Alpha1.VaultSpecSecuritycontextArgs>? SecurityContext { get; set; }

        [Input("serviceAccount")]
        public Input<string>? ServiceAccount { get; set; }

        [Input("serviceMonitorEnabled")]
        public Input<bool>? ServiceMonitorEnabled { get; set; }

        [Input("servicePorts")]
        private InputMap<int>? _servicePorts;
        public InputMap<int> ServicePorts
        {
            get => _servicePorts ?? (_servicePorts = new InputMap<int>());
            set => _servicePorts = value;
        }

        [Input("serviceRegistrationEnabled")]
        public Input<bool>? ServiceRegistrationEnabled { get; set; }

        [Input("serviceType")]
        public Input<string>? ServiceType { get; set; }

        [Input("sidecarEnvsConfig")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Vault.V1Alpha1.VaultSpecSidecarenvsconfigArgs>? _sidecarEnvsConfig;
        public InputList<Pulumi.Kubernetes.Types.Inputs.Vault.V1Alpha1.VaultSpecSidecarenvsconfigArgs> SidecarEnvsConfig
        {
            get => _sidecarEnvsConfig ?? (_sidecarEnvsConfig = new InputList<Pulumi.Kubernetes.Types.Inputs.Vault.V1Alpha1.VaultSpecSidecarenvsconfigArgs>());
            set => _sidecarEnvsConfig = value;
        }

        [Input("size")]
        public Input<int>? Size { get; set; }

        [Input("statsdConfig")]
        public Input<string>? StatsdConfig { get; set; }

        [Input("statsdDisabled")]
        public Input<bool>? StatsdDisabled { get; set; }

        [Input("statsdImage")]
        public Input<string>? StatsdImage { get; set; }

        [Input("tlsAdditionalHosts")]
        private InputList<string>? _tlsAdditionalHosts;
        public InputList<string> TlsAdditionalHosts
        {
            get => _tlsAdditionalHosts ?? (_tlsAdditionalHosts = new InputList<string>());
            set => _tlsAdditionalHosts = value;
        }

        [Input("tlsExpiryThreshold")]
        public Input<string>? TlsExpiryThreshold { get; set; }

        [Input("tolerations")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Vault.V1Alpha1.VaultSpecTolerationsArgs>? _tolerations;
        public InputList<Pulumi.Kubernetes.Types.Inputs.Vault.V1Alpha1.VaultSpecTolerationsArgs> Tolerations
        {
            get => _tolerations ?? (_tolerations = new InputList<Pulumi.Kubernetes.Types.Inputs.Vault.V1Alpha1.VaultSpecTolerationsArgs>());
            set => _tolerations = value;
        }

        [Input("unsealConfig")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Vault.V1Alpha1.VaultSpecUnsealconfigArgs>? UnsealConfig { get; set; }

        [Input("vaultAnnotations")]
        private InputMap<string>? _vaultAnnotations;
        public InputMap<string> VaultAnnotations
        {
            get => _vaultAnnotations ?? (_vaultAnnotations = new InputMap<string>());
            set => _vaultAnnotations = value;
        }

        [Input("vaultConfigurerAnnotations")]
        private InputMap<string>? _vaultConfigurerAnnotations;
        public InputMap<string> VaultConfigurerAnnotations
        {
            get => _vaultConfigurerAnnotations ?? (_vaultConfigurerAnnotations = new InputMap<string>());
            set => _vaultConfigurerAnnotations = value;
        }

        [Input("vaultConfigurerLabels")]
        private InputMap<string>? _vaultConfigurerLabels;
        public InputMap<string> VaultConfigurerLabels
        {
            get => _vaultConfigurerLabels ?? (_vaultConfigurerLabels = new InputMap<string>());
            set => _vaultConfigurerLabels = value;
        }

        [Input("vaultConfigurerPodSpec")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Vault.V1Alpha1.VaultSpecVaultconfigurerpodspecArgs>? VaultConfigurerPodSpec { get; set; }

        [Input("vaultContainerSpec")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Vault.V1Alpha1.VaultSpecVaultcontainerspecArgs>? VaultContainerSpec { get; set; }

        [Input("vaultContainers")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Vault.V1Alpha1.VaultSpecVaultcontainersArgs>? _vaultContainers;
        public InputList<Pulumi.Kubernetes.Types.Inputs.Vault.V1Alpha1.VaultSpecVaultcontainersArgs> VaultContainers
        {
            get => _vaultContainers ?? (_vaultContainers = new InputList<Pulumi.Kubernetes.Types.Inputs.Vault.V1Alpha1.VaultSpecVaultcontainersArgs>());
            set => _vaultContainers = value;
        }

        [Input("vaultEnvsConfig")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Vault.V1Alpha1.VaultSpecVaultenvsconfigArgs>? _vaultEnvsConfig;
        public InputList<Pulumi.Kubernetes.Types.Inputs.Vault.V1Alpha1.VaultSpecVaultenvsconfigArgs> VaultEnvsConfig
        {
            get => _vaultEnvsConfig ?? (_vaultEnvsConfig = new InputList<Pulumi.Kubernetes.Types.Inputs.Vault.V1Alpha1.VaultSpecVaultenvsconfigArgs>());
            set => _vaultEnvsConfig = value;
        }

        [Input("vaultInitContainers")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Vault.V1Alpha1.VaultSpecVaultinitcontainersArgs>? _vaultInitContainers;
        public InputList<Pulumi.Kubernetes.Types.Inputs.Vault.V1Alpha1.VaultSpecVaultinitcontainersArgs> VaultInitContainers
        {
            get => _vaultInitContainers ?? (_vaultInitContainers = new InputList<Pulumi.Kubernetes.Types.Inputs.Vault.V1Alpha1.VaultSpecVaultinitcontainersArgs>());
            set => _vaultInitContainers = value;
        }

        [Input("vaultLabels")]
        private InputMap<string>? _vaultLabels;
        public InputMap<string> VaultLabels
        {
            get => _vaultLabels ?? (_vaultLabels = new InputMap<string>());
            set => _vaultLabels = value;
        }

        [Input("vaultPodSpec")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Vault.V1Alpha1.VaultSpecVaultpodspecArgs>? VaultPodSpec { get; set; }

        [Input("veleroEnabled")]
        public Input<bool>? VeleroEnabled { get; set; }

        [Input("veleroFsfreezeImage")]
        public Input<string>? VeleroFsfreezeImage { get; set; }

        [Input("volumeClaimTemplates")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Vault.V1Alpha1.VaultSpecVolumeclaimtemplatesArgs>? _volumeClaimTemplates;
        public InputList<Pulumi.Kubernetes.Types.Inputs.Vault.V1Alpha1.VaultSpecVolumeclaimtemplatesArgs> VolumeClaimTemplates
        {
            get => _volumeClaimTemplates ?? (_volumeClaimTemplates = new InputList<Pulumi.Kubernetes.Types.Inputs.Vault.V1Alpha1.VaultSpecVolumeclaimtemplatesArgs>());
            set => _volumeClaimTemplates = value;
        }

        [Input("volumeMounts")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Vault.V1Alpha1.VaultSpecVolumemountsArgs>? _volumeMounts;
        public InputList<Pulumi.Kubernetes.Types.Inputs.Vault.V1Alpha1.VaultSpecVolumemountsArgs> VolumeMounts
        {
            get => _volumeMounts ?? (_volumeMounts = new InputList<Pulumi.Kubernetes.Types.Inputs.Vault.V1Alpha1.VaultSpecVolumemountsArgs>());
            set => _volumeMounts = value;
        }

        [Input("volumes")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Vault.V1Alpha1.VaultSpecVolumesArgs>? _volumes;
        public InputList<Pulumi.Kubernetes.Types.Inputs.Vault.V1Alpha1.VaultSpecVolumesArgs> Volumes
        {
            get => _volumes ?? (_volumes = new InputList<Pulumi.Kubernetes.Types.Inputs.Vault.V1Alpha1.VaultSpecVolumesArgs>());
            set => _volumes = value;
        }

        [Input("watchedSecretsAnnotations")]
        private InputList<ImmutableDictionary<string, string>>? _watchedSecretsAnnotations;
        public InputList<ImmutableDictionary<string, string>> WatchedSecretsAnnotations
        {
            get => _watchedSecretsAnnotations ?? (_watchedSecretsAnnotations = new InputList<ImmutableDictionary<string, string>>());
            set => _watchedSecretsAnnotations = value;
        }

        [Input("watchedSecretsLabels")]
        private InputList<ImmutableDictionary<string, string>>? _watchedSecretsLabels;
        public InputList<ImmutableDictionary<string, string>> WatchedSecretsLabels
        {
            get => _watchedSecretsLabels ?? (_watchedSecretsLabels = new InputList<ImmutableDictionary<string, string>>());
            set => _watchedSecretsLabels = value;
        }

        public VaultSpecArgs()
        {
        }
        public static new VaultSpecArgs Empty => new VaultSpecArgs();
    }
}
