// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Vault.V1Alpha1
{

    public class VaultSpecUnsealconfigArgs : global::Pulumi.ResourceArgs
    {
        [Input("alibaba")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Vault.V1Alpha1.VaultSpecUnsealconfigAlibabaArgs>? Alibaba { get; set; }

        [Input("aws")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Vault.V1Alpha1.VaultSpecUnsealconfigAwsArgs>? Aws { get; set; }

        [Input("azure")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Vault.V1Alpha1.VaultSpecUnsealconfigAzureArgs>? Azure { get; set; }

        [Input("google")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Vault.V1Alpha1.VaultSpecUnsealconfigGoogleArgs>? Google { get; set; }

        [Input("hsm")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Vault.V1Alpha1.VaultSpecUnsealconfigHsmArgs>? Hsm { get; set; }

        [Input("kubernetes")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Vault.V1Alpha1.VaultSpecUnsealconfigKubernetesArgs>? Kubernetes { get; set; }

        [Input("options")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Vault.V1Alpha1.VaultSpecUnsealconfigOptionsArgs>? Options { get; set; }

        [Input("vault")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Vault.V1Alpha1.VaultSpecUnsealconfigVaultArgs>? Vault { get; set; }

        public VaultSpecUnsealconfigArgs()
        {
        }
        public static new VaultSpecUnsealconfigArgs Empty => new VaultSpecUnsealconfigArgs();
    }
}
