// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Vault.V1Alpha1
{

    public class VaultSpecUnsealconfigAlibabaArgs : global::Pulumi.ResourceArgs
    {
        [Input("kmsKeyId", required: true)]
        public Input<string> KmsKeyId { get; set; } = null!;

        [Input("kmsRegion", required: true)]
        public Input<string> KmsRegion { get; set; } = null!;

        [Input("ossBucket", required: true)]
        public Input<string> OssBucket { get; set; } = null!;

        [Input("ossEndpoint", required: true)]
        public Input<string> OssEndpoint { get; set; } = null!;

        [Input("ossPrefix", required: true)]
        public Input<string> OssPrefix { get; set; } = null!;

        public VaultSpecUnsealconfigAlibabaArgs()
        {
        }
        public static new VaultSpecUnsealconfigAlibabaArgs Empty => new VaultSpecUnsealconfigAlibabaArgs();
    }
}
