// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

namespace Pulumi.Kubernetes.Types.Outputs.Monitoring.V1
{

    /// <summary>
    /// BasicAuth allow an endpoint to authenticate over basic authentication. More info: https://prometheus.io/docs/operating/configuration/#endpoint
    /// </summary>
    [OutputType]
    public sealed class ProbeSpecBasicauth
    {
        /// <summary>
        /// The secret in the service monitor namespace that contains the password for authentication.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Monitoring.V1.ProbeSpecBasicauthPassword Password;
        /// <summary>
        /// The secret in the service monitor namespace that contains the username for authentication.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Monitoring.V1.ProbeSpecBasicauthUsername Username;

        [OutputConstructor]
        private ProbeSpecBasicauth(
            Pulumi.Kubernetes.Types.Outputs.Monitoring.V1.ProbeSpecBasicauthPassword password,

            Pulumi.Kubernetes.Types.Outputs.Monitoring.V1.ProbeSpecBasicauthUsername username)
        {
            Password = password;
            Username = username;
        }
    }
}
