// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System.Collections.Immutable;

namespace Pulumi.Kubernetes.Types.Outputs.Monitoring.V1
{

    /// <summary>
    /// Specification of desired alerting rule definitions for Prometheus.
    /// </summary>
    [OutputType]
    public sealed class PrometheusRuleSpec
    {
        /// <summary>
        /// Content of Prometheus rule file
        /// </summary>
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Monitoring.V1.PrometheusRuleSpecGroups> Groups;

        [OutputConstructor]
        private PrometheusRuleSpec(ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Monitoring.V1.PrometheusRuleSpecGroups> groups)
        {
            Groups = groups;
        }
    }
}
