// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Postgresql.V1
{

    /// <summary>
    /// Resources requirements of every generated Pod. Please refer to https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/ for more information.
    /// </summary>
    public class ClusterSpecResourcesArgs : global::Pulumi.ResourceArgs
    {
        [Input("claims")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Postgresql.V1.ClusterSpecResourcesClaimsArgs>? _claims;

        /// <summary>
        /// Claims lists the names of resources, defined in spec.resourceClaims, that are used by this container. 
        ///  This is an alpha field and requires enabling the DynamicResourceAllocation feature gate. 
        ///  This field is immutable.
        /// </summary>
        public InputList<Pulumi.Kubernetes.Types.Inputs.Postgresql.V1.ClusterSpecResourcesClaimsArgs> Claims
        {
            get => _claims ?? (_claims = new InputList<Pulumi.Kubernetes.Types.Inputs.Postgresql.V1.ClusterSpecResourcesClaimsArgs>());
            set => _claims = value;
        }

        [Input("limits")]
        private InputMap<Union<int, string>>? _limits;

        /// <summary>
        /// Limits describes the maximum amount of compute resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        /// </summary>
        public InputMap<Union<int, string>> Limits
        {
            get => _limits ?? (_limits = new InputMap<Union<int, string>>());
            set => _limits = value;
        }

        [Input("requests")]
        private InputMap<Union<int, string>>? _requests;

        /// <summary>
        /// Requests describes the minimum amount of compute resources required. If Requests is omitted for a container, it defaults to Limits if that is explicitly specified, otherwise to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        /// </summary>
        public InputMap<Union<int, string>> Requests
        {
            get => _requests ?? (_requests = new InputMap<Union<int, string>>());
            set => _requests = value;
        }

        public ClusterSpecResourcesArgs()
        {
        }
        public static new ClusterSpecResourcesArgs Empty => new ClusterSpecResourcesArgs();
    }
}
