// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Postgresql.V1
{

    /// <summary>
    /// Options to specify LDAP configuration
    /// </summary>
    public class ClusterSpecPostgresqlLdapArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Bind as authentication configuration
        /// </summary>
        [Input("bindAsAuth")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Postgresql.V1.ClusterSpecPostgresqlLdapBindasauthArgs>? BindAsAuth { get; set; }

        /// <summary>
        /// Bind+Search authentication configuration
        /// </summary>
        [Input("bindSearchAuth")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Postgresql.V1.ClusterSpecPostgresqlLdapBindsearchauthArgs>? BindSearchAuth { get; set; }

        /// <summary>
        /// LDAP server port
        /// </summary>
        [Input("port")]
        public Input<int>? Port { get; set; }

        /// <summary>
        /// LDAP schema to be used, possible options are `ldap` and `ldaps`
        /// </summary>
        [Input("scheme")]
        public Input<string>? Scheme { get; set; }

        /// <summary>
        /// LDAP hostname or IP address
        /// </summary>
        [Input("server")]
        public Input<string>? Server { get; set; }

        /// <summary>
        /// Set to 'true' to enable LDAP over TLS. 'false' is default
        /// </summary>
        [Input("tls")]
        public Input<bool>? Tls { get; set; }

        public ClusterSpecPostgresqlLdapArgs()
        {
        }
        public static new ClusterSpecPostgresqlLdapArgs Empty => new ClusterSpecPostgresqlLdapArgs();
    }
}
