// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Postgresql.V1
{

    /// <summary>
    /// InstanceReportedState describes the last reported state of an instance during a reconciliation loop
    /// </summary>
    public class ClusterStatusInstancesreportedstateArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// indicates if an instance is the primary one
        /// </summary>
        [Input("isPrimary", required: true)]
        public Input<bool> IsPrimary { get; set; } = null!;

        /// <summary>
        /// indicates on which TimelineId the instance is
        /// </summary>
        [Input("timeLineID")]
        public Input<int>? TimeLineID { get; set; }

        public ClusterStatusInstancesreportedstateArgs()
        {
        }
        public static new ClusterStatusInstancesreportedstateArgs Empty => new ClusterStatusInstancesreportedstateArgs();
    }
}
