// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Postgresql.V1
{

    /// <summary>
    /// This is the cluster reference on which the Pooler will work. Pooler name should never match with any cluster name within the same namespace.
    /// </summary>
    public class PoolerSpecClusterArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Name of the referent.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public PoolerSpecClusterArgs()
        {
        }
        public static new PoolerSpecClusterArgs Empty => new PoolerSpecClusterArgs();
    }
}
