// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Postgresql.V1
{

    /// <summary>
    /// Specification of the desired behavior of the ScheduledBackup. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status
    /// </summary>
    public class ScheduledBackupSpecArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Indicates which ownerReference should be put inside the created backup resources.&lt;br /&gt; - none: no owner reference for created backup objects (same behavior as before the field was introduced)&lt;br /&gt; - self: sets the Scheduled backup object as owner of the backup&lt;br /&gt; - cluster: set the cluster as owner of the backup&lt;br /&gt;
        /// </summary>
        [Input("backupOwnerReference")]
        public Input<string>? BackupOwnerReference { get; set; }

        /// <summary>
        /// The cluster to backup
        /// </summary>
        [Input("cluster")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Postgresql.V1.ScheduledBackupSpecClusterArgs>? Cluster { get; set; }

        /// <summary>
        /// If the first backup has to be immediately start after creation or not
        /// </summary>
        [Input("immediate")]
        public Input<bool>? Immediate { get; set; }

        /// <summary>
        /// The schedule does not follow the same format used in Kubernetes CronJobs as it includes an additional seconds specifier, see https://pkg.go.dev/github.com/robfig/cron#hdr-CRON_Expression_Format
        /// </summary>
        [Input("schedule", required: true)]
        public Input<string> Schedule { get; set; } = null!;

        /// <summary>
        /// If this backup is suspended or not
        /// </summary>
        [Input("suspend")]
        public Input<bool>? Suspend { get; set; }

        /// <summary>
        /// The policy to decide which instance should perform this backup. If empty, it defaults to `cluster.spec.backup.target`. Available options are empty string, which will default to `primary` policy, `primary` to have backups run always on primary instances, `prefer-standby` to have backups run preferably on the most updated standby, if available.
        /// </summary>
        [Input("target")]
        public Input<string>? Target { get; set; }

        public ScheduledBackupSpecArgs()
        {
            BackupOwnerReference = "none";
        }
        public static new ScheduledBackupSpecArgs Empty => new ScheduledBackupSpecArgs();
    }
}
